# fly.toml app configuration file generated for miniflux-to-discord-8345 on 2026-03-24T17:46:14+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'miniflux-to-discord-8345'
primary_region = 'syd'

[build]

[env]
  LISTEN_HOST = '0.0.0.0'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpus = 1
  memory_mb = 256
